package DiDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_All;
  private ConceptPresentation props_BasedOn;
  private ConceptPresentation props_CheckParallelTrendsStaggered;
  private ConceptPresentation props_ColumnReference;
  private ConceptPresentation props_ComputePrePostMeans;
  private ConceptPresentation props_EmptyLine;
  private ConceptPresentation props_GroupColumnClause;
  private ConceptPresentation props_IColumnClause;
  private ConceptPresentation props_IReferenceOutcomeColumn;
  private ConceptPresentation props_ImputeMissingMultiple;
  private ConceptPresentation props_LoadDataset;
  private ConceptPresentation props_Omit;
  private ConceptPresentation props_PValue;
  private ConceptPresentation props_PlotEventStudyMeans;
  private ConceptPresentation props_RunAttEstimations;
  private ConceptPresentation props_Script;
  private ConceptPresentation props_Set;
  private ConceptPresentation props_SetCovariates;
  private ConceptPresentation props_ShowDataset;
  private ConceptPresentation props_SignificanceLevel;
  private ConceptPresentation props_Statement;
  private ConceptPresentation props_TimeColumnClause;
  private ConceptPresentation props_TreatmentValues;
  private ConceptPresentation props_Using;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.All:
        if (props_All == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Optional clause for Show Dataset, it allows showing the entire dataset");
          cpb.rawPresentation("all");
          props_All = cpb.create();
        }
        return props_All;
      case LanguageConceptSwitch.BasedOn:
        if (props_BasedOn == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("based on");
          props_BasedOn = cpb.create();
        }
        return props_BasedOn;
      case LanguageConceptSwitch.CheckParallelTrendsStaggered:
        if (props_CheckParallelTrendsStaggered == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("check parallel trends staggered");
          props_CheckParallelTrendsStaggered = cpb.create();
        }
        return props_CheckParallelTrendsStaggered;
      case LanguageConceptSwitch.ColumnReference:
        if (props_ColumnReference == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x43695e8c6851034aL, 0x43695e8c6851034bL, "column", "", "");
          props_ColumnReference = cpb.create();
        }
        return props_ColumnReference;
      case LanguageConceptSwitch.ComputePrePostMeans:
        if (props_ComputePrePostMeans == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Computes and displays average value of an outcome variable in the pre- and post- treatment periods, separately for each treatment group ");
          cpb.rawPresentation("compute pre post means");
          props_ComputePrePostMeans = cpb.create();
        }
        return props_ComputePrePostMeans;
      case LanguageConceptSwitch.EmptyLine:
        if (props_EmptyLine == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("EmptyLine");
          props_EmptyLine = cpb.create();
        }
        return props_EmptyLine;
      case LanguageConceptSwitch.GroupColumnClause:
        if (props_GroupColumnClause == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Optional clause of set command for setting treatment values when column set is group");
          cpb.rawPresentation("GroupColumnClause");
          props_GroupColumnClause = cpb.create();
        }
        return props_GroupColumnClause;
      case LanguageConceptSwitch.IColumnClause:
        if (props_IColumnClause == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_IColumnClause = cpb.create();
        }
        return props_IColumnClause;
      case LanguageConceptSwitch.IReferenceOutcomeColumn:
        if (props_IReferenceOutcomeColumn == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_IReferenceOutcomeColumn = cpb.create();
        }
        return props_IReferenceOutcomeColumn;
      case LanguageConceptSwitch.ImputeMissingMultiple:
        if (props_ImputeMissingMultiple == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Replaces NaN or missing values in a certain column by the mean of that column computed over an appropriate reference group, defined by the treatment group identifier and a binary indicator for pre- vs post- treatment periods derived from column time");
          cpb.rawPresentation("impute missing data for");
          props_ImputeMissingMultiple = cpb.create();
        }
        return props_ImputeMissingMultiple;
      case LanguageConceptSwitch.LoadDataset:
        if (props_LoadDataset == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Loads a csv file as a dataset from a specified file and assigns it a name for later use");
          cpb.presentationByName();
          props_LoadDataset = cpb.create();
        }
        return props_LoadDataset;
      case LanguageConceptSwitch.Omit:
        if (props_Omit == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Omit");
          props_Omit = cpb.create();
        }
        return props_Omit;
      case LanguageConceptSwitch.PValue:
        if (props_PValue == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("PValue");
          props_PValue = cpb.create();
        }
        return props_PValue;
      case LanguageConceptSwitch.PlotEventStudyMeans:
        if (props_PlotEventStudyMeans == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("plot eventstudy means");
          props_PlotEventStudyMeans = cpb.create();
        }
        return props_PlotEventStudyMeans;
      case LanguageConceptSwitch.RunAttEstimations:
        if (props_RunAttEstimations == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("run att estimations");
          props_RunAttEstimations = cpb.create();
        }
        return props_RunAttEstimations;
      case LanguageConceptSwitch.Script:
        if (props_Script == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Script");
          props_Script = cpb.create();
        }
        return props_Script;
      case LanguageConceptSwitch.Set:
        if (props_Set == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Command for setting different column values using column types");
          cpb.presentationByName();
          props_Set = cpb.create();
        }
        return props_Set;
      case LanguageConceptSwitch.SetCovariates:
        if (props_SetCovariates == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Command for seting covariates");
          cpb.presentationByName();
          props_SetCovariates = cpb.create();
        }
        return props_SetCovariates;
      case LanguageConceptSwitch.ShowDataset:
        if (props_ShowDataset == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Command for showing the dataset partially (10 rows if ShowRows omitted) or totally");
          cpb.rawPresentation("show dataset");
          props_ShowDataset = cpb.create();
        }
        return props_ShowDataset;
      case LanguageConceptSwitch.SignificanceLevel:
        if (props_SignificanceLevel == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("alpha");
          props_SignificanceLevel = cpb.create();
        }
        return props_SignificanceLevel;
      case LanguageConceptSwitch.Statement:
        if (props_Statement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Statement = cpb.create();
        }
        return props_Statement;
      case LanguageConceptSwitch.TimeColumnClause:
        if (props_TimeColumnClause == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Optional clause for Set command when applied to time column, it is used for setting pre and post time periods");
          cpb.rawPresentation("TimeColumnClause");
          props_TimeColumnClause = cpb.create();
        }
        return props_TimeColumnClause;
      case LanguageConceptSwitch.TreatmentValues:
        if (props_TreatmentValues == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("with treatment values");
          props_TreatmentValues = cpb.create();
        }
        return props_TreatmentValues;
      case LanguageConceptSwitch.Using:
        if (props_Using == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("using");
          props_Using = cpb.create();
        }
        return props_Using;
    }
    return null;
  }
}
