package DiDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ColumnType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ColumnType() {
    super(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x3d7090ceae12b0adL, "ColumnType", "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/4427197651063320749");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_id_0 = new EnumerationDescriptor.MemberDescriptor("id", "id", 0x3d7090ceae12b0afL, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/4427197651063320751");
  private final EnumerationDescriptor.MemberDescriptor myMember_group_0 = new EnumerationDescriptor.MemberDescriptor("group", "group", 0x3d7090ceae12b0b0L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/4427197651063320752");
  private final EnumerationDescriptor.MemberDescriptor myMember_time_0 = new EnumerationDescriptor.MemberDescriptor("time", "time", 0x3d7090ceae12b0b1L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/4427197651063320753");
  private final EnumerationDescriptor.MemberDescriptor myMember_outcome_0 = new EnumerationDescriptor.MemberDescriptor("outcome", "outcome", 0x3d7090ceae12b0b3L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/4427197651063320755");
  private final EnumerationDescriptor.MemberDescriptor myMember_subgroup_0 = new EnumerationDescriptor.MemberDescriptor("subgroup", "subgroup", 0x165025d304908309L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/1607826655216173833");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x3d7090ceae12b0adL, 0x3d7090ceae12b0afL, 0x3d7090ceae12b0b0L, 0x3d7090ceae12b0b1L, 0x3d7090ceae12b0b3L, 0x165025d304908309L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_id_0, myMember_group_0, myMember_time_0, myMember_outcome_0, myMember_subgroup_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "id":
        return myMember_id_0;
      case "group":
        return myMember_group_0;
      case "time":
        return myMember_time_0;
      case "outcome":
        return myMember_outcome_0;
      case "subgroup":
        return myMember_subgroup_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
