package DiDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EstimationMethod extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EstimationMethod() {
    super(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8b0e429aL, "EstimationMethod", "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276384080538");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_DR_0 = new EnumerationDescriptor.MemberDescriptor("DR", "DR", 0x32a4f45c8b0e429bL, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276384080539");
  private final EnumerationDescriptor.MemberDescriptor myMember_IPW_0 = new EnumerationDescriptor.MemberDescriptor("IPW", "IPW", 0x32a4f45c8b0e429eL, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276384080542");
  private final EnumerationDescriptor.MemberDescriptor myMember_OR_0 = new EnumerationDescriptor.MemberDescriptor("OR", "OR", 0x32a4f45c8b0e42a0L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276384080544");
  private final EnumerationDescriptor.MemberDescriptor myMember_GT_0 = new EnumerationDescriptor.MemberDescriptor("GT", "GT", 0x32a4f45c8b0e42a2L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276384080546");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8b0e429aL, 0x32a4f45c8b0e429bL, 0x32a4f45c8b0e429eL, 0x32a4f45c8b0e42a0L, 0x32a4f45c8b0e42a2L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_DR_0, myMember_IPW_0, myMember_OR_0, myMember_GT_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_DR_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "DR":
        return myMember_DR_0;
      case "IPW":
        return myMember_IPW_0;
      case "OR":
        return myMember_OR_0;
      case "GT":
        return myMember_GT_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
