package DiDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ClusteringType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ClusteringType() {
    super(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8ade105dL, "ClusteringType", "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276380921949");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_robust_0 = new EnumerationDescriptor.MemberDescriptor("robust", "robust", 0x32a4f45c8ade105eL, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276380921950");
  private final EnumerationDescriptor.MemberDescriptor myMember_clustered_id_0 = new EnumerationDescriptor.MemberDescriptor("clustered_id", "clustered_id", 0x32a4f45c8ade1060L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276380921952");
  private final EnumerationDescriptor.MemberDescriptor myMember_clustered_by_0 = new EnumerationDescriptor.MemberDescriptor("clustered_by", "clustered_by", 0x32a4f45c8ade1062L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276380921954");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8ade105dL, 0x32a4f45c8ade105eL, 0x32a4f45c8ade1060L, 0x32a4f45c8ade1062L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_robust_0, myMember_clustered_id_0, myMember_clustered_by_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "robust":
        return myMember_robust_0;
      case "clustered_id":
        return myMember_clustered_id_0;
      case "clustered_by":
        return myMember_clustered_by_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
