package DiDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CSVHeader extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CSVHeader() {
    super(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8b0765f7L, "CSVHeader", "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276383630839");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_with_0 = new EnumerationDescriptor.MemberDescriptor("with", "with header", 0x32a4f45c8b0765f8L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276383630840");
  private final EnumerationDescriptor.MemberDescriptor myMember_without_0 = new EnumerationDescriptor.MemberDescriptor("without", "without header", 0x32a4f45c8b0765f9L, "r:fddcec65-b03d-485e-ad0f-90dc64caa764(DiDSL.structure)/3649310276383630841");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8b0765f7L, 0x32a4f45c8b0765f8L, 0x32a4f45c8b0765f9L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_with_0, myMember_without_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_with_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "with":
        return myMember_with_0;
      case "without":
        return myMember_without_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
