package DiDSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int All = 0;
  public static final int BasedOn = 1;
  public static final int CheckParallelTrendsStaggered = 2;
  public static final int Column = 3;
  public static final int ColumnReference = 4;
  public static final int ComputePrePostMeans = 5;
  public static final int Covariates = 6;
  public static final int EmptyLine = 7;
  public static final int Exclude = 8;
  public static final int GroupColumnClause = 9;
  public static final int IColumnClause = 10;
  public static final int IReferenceOutcomeColumn = 11;
  public static final int ImputeMissingMultiple = 12;
  public static final int Include = 13;
  public static final int LoadDataset = 14;
  public static final int Omit = 15;
  public static final int PlotEventStudyMeans = 16;
  public static final int RunAttEstimations = 17;
  public static final int Script = 18;
  public static final int Set = 19;
  public static final int SetCovariates = 20;
  public static final int ShowDataset = 21;
  public static final int Statement = 22;
  public static final int TimeColumnClause = 23;
  public static final int TreatmentValues = 24;
  public static final int Using = 25;
  public static final int With = 26;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe61e3c2843b94790L, 0x9950a30830b7e20fL);
    builder.put(0x32a4f45c8acf7e13L, All);
    builder.put(0x780e609f84c7c293L, BasedOn);
    builder.put(0x32a4f45c8ade1065L, CheckParallelTrendsStaggered);
    builder.put(0x334c23d60f2d704fL, Column);
    builder.put(0x43695e8c6851034aL, ColumnReference);
    builder.put(0x32a4f45c8ad2065eL, ComputePrePostMeans);
    builder.put(0x165025d3045ddecaL, Covariates);
    builder.put(0x43695e8c686579c3L, EmptyLine);
    builder.put(0x165025d3046eda57L, Exclude);
    builder.put(0x32a4f45c8acd44b5L, GroupColumnClause);
    builder.put(0x43695e8c684875d3L, IColumnClause);
    builder.put(0x43695e8c6843ccc1L, IReferenceOutcomeColumn);
    builder.put(0x32a4f45c8ad115bcL, ImputeMissingMultiple);
    builder.put(0x165025d3047230a9L, Include);
    builder.put(0x3d7090ceae0fe3ccL, LoadDataset);
    builder.put(0x43695e8c68521db3L, Omit);
    builder.put(0x32a4f45c8adcc6dbL, PlotEventStudyMeans);
    builder.put(0x32a4f45c8b0e4315L, RunAttEstimations);
    builder.put(0x3d7090ceae0fe3c3L, Script);
    builder.put(0x3d7090ceae11373cL, Set);
    builder.put(0x32a4f45c8aceccefL, SetCovariates);
    builder.put(0x32a4f45c8acf7e0cL, ShowDataset);
    builder.put(0x3d7090ceae0fe3c5L, Statement);
    builder.put(0x32a4f45c8acd44c1L, TimeColumnClause);
    builder.put(0x32a4f45c8aca9c81L, TreatmentValues);
    builder.put(0x43695e8c685102d7L, Using);
    builder.put(0x165025d303be93d4L, With);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
