package DiDSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CheckParallelTrendsStaggered = 0;
  public static final int ComputePrePostMeans = 1;
  public static final int GroupColumnClause = 2;
  public static final int ImputeMissingMultiple = 3;
  public static final int LoadDataset = 4;
  public static final int OutcomeColumn = 5;
  public static final int PValue = 6;
  public static final int PlotEventStudyMeans = 7;
  public static final int RunAttEstimations = 8;
  public static final int Script = 9;
  public static final int Set = 10;
  public static final int SetCovariates = 11;
  public static final int ShowDataset = 12;
  public static final int ShowRows = 13;
  public static final int SignificanceLevel = 14;
  public static final int Statement = 15;
  public static final int TimeColumnClause = 16;
  public static final int TreatmentValues = 17;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe61e3c2843b94790L, 0x9950a30830b7e20fL);
    builder.put(0x32a4f45c8ade1065L, CheckParallelTrendsStaggered);
    builder.put(0x32a4f45c8ad2065eL, ComputePrePostMeans);
    builder.put(0x32a4f45c8acd44b5L, GroupColumnClause);
    builder.put(0x32a4f45c8ad115bcL, ImputeMissingMultiple);
    builder.put(0x3d7090ceae0fe3ccL, LoadDataset);
    builder.put(0x32a4f45c8adb78daL, OutcomeColumn);
    builder.put(0x32a4f45c8ade1095L, PValue);
    builder.put(0x32a4f45c8adcc6dbL, PlotEventStudyMeans);
    builder.put(0x32a4f45c8b0e4315L, RunAttEstimations);
    builder.put(0x3d7090ceae0fe3c3L, Script);
    builder.put(0x3d7090ceae11373cL, Set);
    builder.put(0x32a4f45c8aceccefL, SetCovariates);
    builder.put(0x32a4f45c8acf7e0cL, ShowDataset);
    builder.put(0x32a4f45c8acf7e13L, ShowRows);
    builder.put(0x32a4f45c8b0e435dL, SignificanceLevel);
    builder.put(0x3d7090ceae0fe3c5L, Statement);
    builder.put(0x32a4f45c8acd44c1L, TimeColumnClause);
    builder.put(0x32a4f45c8aca9c81L, TreatmentValues);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
