package DiDSL.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_SetCovariates_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_SetCovariates_NonTypesystemRule() {
  }
  public void applyRule(final SNode setCovariates, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    for (SNode column : ListSequence.fromList(SLinkOperations.getChildren(setCovariates, LINKS.columnList$QBAT))) {
      if (SNodeOperations.getParent(SLinkOperations.getTarget(column, LINKS.column$yo5j)) != SLinkOperations.getTarget(setCovariates, LINKS.dataset$Ldkh)) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(setCovariates, "Dataset is different from the expected one", "r:ad55364e-4a37-4c47-b02e-004b1fbd2e17(DiDSL.typesystem)", "3696368796453377468", null, errorTarget);
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.SetCovariates$e_;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink dataset$Ldkh = MetaAdapterFactory.getReferenceLink(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8aceccefL, 0x334c23d60f68045cL, "dataset");
    /*package*/ static final SReferenceLink column$yo5j = MetaAdapterFactory.getReferenceLink(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x43695e8c6851034aL, 0x43695e8c6851034bL, "column");
    /*package*/ static final SContainmentLink columnList$QBAT = MetaAdapterFactory.getContainmentLink(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8aceccefL, 0x334c23d60f5f2988L, "columnList");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SetCovariates$e_ = MetaAdapterFactory.getConcept(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8aceccefL, "DiDSL.structure.SetCovariates");
  }
}
