package DiDSL.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class BasedOn {
  public static class NodeFactory_8650958172469053440 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      {
        final SNode plotEventStudyMeans = enclosingNode;
        if (SNodeOperations.isInstanceOf(plotEventStudyMeans, CONCEPTS.PlotEventStudyMeans$tr)) {
          SPropertyOperations.assignEnum(newNode, PROPS.controlStrategy$awon, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8ade1053L, "DiDSL.structure.ControlStrategy"), 0x32a4f45c8ade1058L, "not_yet_treated"));

        }
      }
      {
        final SNode checkParallelTrendsStaggered = enclosingNode;
        if (SNodeOperations.isInstanceOf(checkParallelTrendsStaggered, CONCEPTS.CheckParallelTrendsStaggered$YH)) {
          SPropertyOperations.assignEnum(newNode, PROPS.controlStrategy$awon, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8ade1053L, "DiDSL.structure.ControlStrategy"), 0x32a4f45c8ade1054L, "interaction"));
        }
      }


    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PlotEventStudyMeans$tr = MetaAdapterFactory.getConcept(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8adcc6dbL, "DiDSL.structure.PlotEventStudyMeans");
    /*package*/ static final SConcept CheckParallelTrendsStaggered$YH = MetaAdapterFactory.getConcept(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8ade1065L, "DiDSL.structure.CheckParallelTrendsStaggered");
  }

  private static final class PROPS {
    /*package*/ static final SProperty controlStrategy$awon = MetaAdapterFactory.getProperty(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x780e609f84c7c293L, 0x780e609f84c7c298L, "controlStrategy");
  }
}
