package DiDSL.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class With {
  public static class NodeFactory_1607826655207420923 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      {
        final SNode checkParallelTrendsStaggered = enclosingNode;
        if (SNodeOperations.isInstanceOf(checkParallelTrendsStaggered, CONCEPTS.CheckParallelTrendsStaggered$YH)) {
          SPropertyOperations.assign(newNode, PROPS.pValue$Hmow, "0.05");
        }
      }
      {
        final SNode runAttEstimations = enclosingNode;
        if (SNodeOperations.isInstanceOf(runAttEstimations, CONCEPTS.RunAttEstimations$3)) {
          SPropertyOperations.assign(newNode, PROPS.pValue$Hmow, "0.05");
          SPropertyOperations.assign(newNode, PROPS.alpha$PWTZ, "0.05");
        }
      }
      {
        final SNode loadDataset = enclosingNode;
        if (SNodeOperations.isInstanceOf(loadDataset, CONCEPTS.LoadDataset$ic)) {
          SPropertyOperations.assignEnum(newNode, PROPS.header$AFI2, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8b0765f7L, "DiDSL.structure.CSVHeader"), 0x32a4f45c8b0765f8L, "with"));
        }
      }
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept CheckParallelTrendsStaggered$YH = MetaAdapterFactory.getConcept(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8ade1065L, "DiDSL.structure.CheckParallelTrendsStaggered");
    /*package*/ static final SConcept RunAttEstimations$3 = MetaAdapterFactory.getConcept(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8b0e4315L, "DiDSL.structure.RunAttEstimations");
    /*package*/ static final SConcept LoadDataset$ic = MetaAdapterFactory.getConcept(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x3d7090ceae0fe3ccL, "DiDSL.structure.LoadDataset");
  }

  private static final class PROPS {
    /*package*/ static final SProperty pValue$Hmow = MetaAdapterFactory.getProperty(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x165025d303be93d4L, 0x165025d303d7417eL, "pValue");
    /*package*/ static final SProperty alpha$PWTZ = MetaAdapterFactory.getProperty(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x165025d303be93d4L, 0x165025d303e243f0L, "alpha");
    /*package*/ static final SProperty header$AFI2 = MetaAdapterFactory.getProperty(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x165025d303be93d4L, 0x165025d303fbd93fL, "header");
  }
}
