package ActorLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_WindowType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_WindowType() {
    super(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x712ee2200f5e5c16L, "WindowType", "r:a6f544b3-65b6-4da8-ad8a-228799e10ea8(ActorLanguage.structure)/8155704602539219990");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_TUMBLING_0 = new EnumerationDescriptor.MemberDescriptor("TUMBLING", "TUMBLING", 0x712ee2200f5e5c17L, "r:a6f544b3-65b6-4da8-ad8a-228799e10ea8(ActorLanguage.structure)/8155704602539219991");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x712ee2200f5e5c16L, 0x712ee2200f5e5c17L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_TUMBLING_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_TUMBLING_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "TUMBLING":
        return myMember_TUMBLING_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
