package DiDSL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class IReferenceOutcomeColumn_Constraints extends BaseConstraintsDescriptor {
  /*package*/ IReferenceOutcomeColumn_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.IReferenceOutcomeColumn$8n, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.column$5rZC, container, false, true);
    }
    @Override
    public boolean validate(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      return true;
    }
    @Override
    public void onReferenceSet(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      SLinkOperations.setTarget(referenceNode, LINKS.column$5rZC, newReferentNode);
      SLinkOperations.setTarget(referenceNode, LINKS.dataset$XAK3, SNodeOperations.cast(SNodeOperations.getParent(newReferentNode), CONCEPTS.LoadDataset$ic));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IReferenceOutcomeColumn$8n = MetaAdapterFactory.getInterfaceConcept(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x43695e8c6843ccc1L, "DiDSL.structure.IReferenceOutcomeColumn");
    /*package*/ static final SConcept LoadDataset$ic = MetaAdapterFactory.getConcept(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x3d7090ceae0fe3ccL, "DiDSL.structure.LoadDataset");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink column$5rZC = MetaAdapterFactory.getReferenceLink(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x43695e8c6843ccc1L, 0x43695e8c6843ccc2L, "column");
    /*package*/ static final SReferenceLink dataset$XAK3 = MetaAdapterFactory.getReferenceLink(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x43695e8c6843ccc1L, 0x43695e8c685fdda1L, "dataset");
  }
}
