package DiDSL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class SetCovariates_Constraints extends BaseConstraintsDescriptor {
  /*package*/ SetCovariates_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.SetCovariates$e_, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SetCovariates$e_ = MetaAdapterFactory.getConcept(0xe61e3c2843b94790L, 0x9950a30830b7e20fL, 0x32a4f45c8aceccefL, "DiDSL.structure.SetCovariates");
  }
}
