package ActorLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class EmptyLine_SubstituteMenu extends SubstituteMenuBase {
  public EmptyLine_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "EmptyLine", new SNodePointer("r:69381955-c8b5-4c14-b1e0-ddad66dcca70(ActorLanguage.editor)", "6946180687075350559")));
  }

}
